sudo: required
services:
  - docker
jobs:
  stage: run
    script:
      - echo "asd"
  stage: test
    script:
      - echo "asd"
  stage: deploy
    script:
      - echo "asd"
after_success:
  - echo "Success"
