sudo: required
language: node_js
node_js:
  - 'stable'
services:
  - docker
jobs:
  include:
    - stage: test 
      script:
        - make start 
        - make test
    - stage: deploy 
      script:
        - make start
        - make deploy
