sudo: required
language: node_js
node_js:
  - 'stable'
services:
  - docker
jobs:
  include:
    - stage: run  
      script: 
        - make start  
    - stage: test 
      script:
        - make start 
        - docker-compose exec app -T npm run test
    - stage: deploy 
      script: 
        - make deploy 
after_success:
  - echo "Success"
