sudo: false
language: node_js
node_js:
  - 'node'
  - '6'
  - '5'
  - '4'
jobs:
  stage: run
    script:
      - echo "test"
  stage: test
    script:
      - echo "test"
  stage: deploy
    script:
      - echo deploy
after_success:
  - echo "Success"

