services:
  - docker
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
install: npm install
script: npm run test
deploy:
  provider: script
  script: sh make deploy_ci TARGET=$TARGET AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  on:
    branch: master
